### ISSUE TITLE
mutable_arrays/sel_sort.c

### ISSUE THREAD

**Issue by naayaaru** [manavpatnaik/frama-c-problems#2]
Dear Sir, This is code 
mutable_arrays/sel_sort.c
is not getting verified. There are few unknowns showing.
Please look into it sir. 
Thank You.

**Comment by manavpatnaik** [comment]
> Dear Sir, This is code 
> mutable_arrays/sel_sort.c
> is not getting verified. There are few unknowns showing.
> Please look into it sir. 
> Thank You.

Will look into it
